aiidateam/aiida-cp2k

- MANIFEST.in
```
$ pip install aiida-cp2k
Collecting aiida-cp2k
Downloading aiida_cp2k-0.8.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/var/folders/8y/7c7qkxcx5vxb749rt3sw5sh40000gp/T/pip-build-LB7jBp/aiida-cp2k/setup.py", line 6, in <module>
with open('setup.json', 'r') as info:
IOError: [Errno 2] No such file or directory: 'setup.json'
```
> include setup.json in pypi

- .ci/check_travis_tag.py
- .pre-commit-config.yaml
- .travis.yml
- Dockerfile
- aiida_cp2k/__init__.py
- aiida_cp2k/calculations/__init__.py
- aiida_cp2k/parsers/__init__.py
- setup.json
- test/check_version.py
- test/run_tests.sh
@yakutovicha fixes based on @ltalirz and my review
> Review fixes

- aiida_cp2k/parsers/__init__.py
- test/run_tests.sh
- test/test_bands.py
Add a function that parses band structure if it is present in cp2k output.
> implement bands parsing

- aiida_cp2k/calculations/__init__.py
- aiida_cp2k/parsers/__init__.py
- test/run_tests.sh
- test/test_single_calculation/test_dft_atomic_kinds.py
fixes #32
1) Insert atomic kinds into the input geometry file
(StructureData -> aiida.coord.xyz)
2) Parse atomic kinds from the cp2k restart file and insert
them into kinds of StructureData output object.
3) Add run example to test this functionality
> Manage atomic kinds (tags):

- .gitignore
- LICENSE.txt
- aiida_cp2k/utils/__init__.py
- aiida_cp2k/utils/input_generator.py
- aiida_cp2k/utils/parser.py
- examples/single_calculations/test_bands.py
- examples/single_calculations/test_dft.py
- examples/single_calculations/test_dft_atomic_kinds.py
- examples/single_calculations/test_failure.py
- examples/single_calculations/test_geopt.py
- examples/single_calculations/test_mm.py
- examples/single_calculations/test_multiple_force_eval.py
- examples/single_calculations/test_no_struct.py
- examples/single_calculations/test_precision.py
- examples/single_calculations/test_restart.py
- examples/workchains/test_base.py
fixes #38 
1) Add an extended .gitignore
2) Modify 2018 to 2019 in the LICENSE file
3) utils.py -> folder with input_generator.py and parser.py files.
4) Move examples to click
> Small improvements & reorganizations:

- aiida_cp2k/calculations/__init__.py
> Allow for restart from a different computer

- aiida_cp2k/utils/workchains.py
- aiida_cp2k/workchains/multistage.py
- setup.json
- setup.py
> Fix python2 problems

- Dockerfile
- MANIFEST.in
> Add multistage protocols to pypi release

- examples/single_calculations/example_dft.py
- examples/single_calculations/example_dft_atomic_kinds.py
- examples/single_calculations/example_failure.py
- examples/single_calculations/example_geopt.py
- examples/single_calculations/example_mm.py
- examples/single_calculations/example_multiple_force_eval.py
- examples/single_calculations/example_no_struct.py
- examples/single_calculations/example_precision.py
- examples/single_calculations/example_restart.py
- examples/single_calculations/example_structure_through_file.py
- examples/single_calculations/fixme_bands.py
- examples/workchains/example_base.py
- examples/workchains/example_multistage_Al.py
- examples/workchains/example_multistage_h2o-.py
- examples/workchains/example_multistage_h2o.py
- examples/workchains/example_multistage_h2o_fail.py
- examples/workchains/example_multistage_h2o_singlepoint.py
- examples/workchains/example_multistage_h2o_testfile.py
> change examples to process builder

- aiida_cp2k/parsers/__init__.py
- aiida_cp2k/utils/__init__.py
- aiida_cp2k/utils/parser.py
- aiida_cp2k/utils/workchains.py
- setup.json
- test/outputs/BSSE_output_v5.1_.out
- test/test_parsers.py
This contains work chains to compute binding energies with FF and DFT.
Therefore, it is related to PR to:
* aiida-raspa: https://github.com/yakutovicha/aiida-raspa/pull/46
* aiida-lsmo: https://github.com/lsmo-epfl/aiida-lsmo/pull/23
> add binding calc

- aiida_cp2k/workchains/aiida_base_restart.py
- aiida_cp2k/workchains/multistage.py
Please check and make a new release.
> add lambda for input default

- .docker/my_init.d/add-codes.sh
- .docker/opt/add-codes.sh
- .travis.yml
- Dockerfile
* Update Travis and Docker file
* Install things as root user
> Travis and Docker file updates

- .ci/check_travis_tag.py
- .pre-commit-config.yaml
- .pylintrc
- aiida_cp2k/calculations/__init__.py
- aiida_cp2k/parsers/__init__.py
- aiida_cp2k/utils/__init__.py
- aiida_cp2k/utils/input_generator.py
- aiida_cp2k/utils/parser.py
- aiida_cp2k/utils/workchains.py
- aiida_cp2k/workchains/aiida_base_restart.py
- aiida_cp2k/workchains/base.py
- conftest.py
- examples/single_calculations/example_dft.py
- examples/single_calculations/example_dft_atomic_kinds.py
- examples/single_calculations/example_failure.py
- examples/single_calculations/example_geopt.py
- examples/single_calculations/example_mm.py
- examples/single_calculations/example_multiple_force_eval.py
- examples/single_calculations/example_no_struct.py
- examples/single_calculations/example_precision.py
- examples/single_calculations/example_restart.py
- examples/single_calculations/example_structure_through_file.py
- examples/single_calculations/fixme_bands.py
- examples/workchains/example_base.py
- setup.json
- setup.py
- test/test_input_generator.py
- test/test_version_agreement.py
> Drop Python2 support.

- .coveragerc
- .docker/my_init.d/add-codes.sh
- .docker/opt/add-codes.sh
- .travis.yml
- Dockerfile
- examples/single_calculations/example_restart.py
> Change docker base image to aiida-core.

- aiida_cp2k/calculations/__init__.py
- test/test_xyz.py
testing that tags are handled as expected
(needed to make sure for aiida-lsmo)
> add test for xyz writing

- aiida_cp2k/parsers/__init__.py
- aiida_cp2k/utils/__init__.py
- aiida_cp2k/utils/input_generator.py
- aiida_cp2k/utils/parser.py
- aiida_cp2k/workchains/base.py
- examples/single_calculations/example_restart.py
- examples/workchains/example_base_failed_restart.py
- examples/workchains/example_base_restart.py
For this:
- Standardize parsers.
- Add two separate functions to add wfn restart and external restart.
- Make parsers more standard.
> Prepare new restart_incomplete_calculation handler.

- pyproject.toml
The tool was replaced by flake8.
> Remove pylint config.

- aiida_cp2k/workchains/base.py
- examples/workchains/example_base_energy_restart.py
- examples/workchains/example_base_failed_restart.py
- examples/workchains/example_base_geoopt_restart.py
- examples/workchains/example_base_scf_restart.py
The new conditions ask for the end of SCF inner cycle with "Total energy:", This guarantees that there is *.wfn file in the directory
> Adding a extra condition to restart_incomplete_calcution

- aiida_cp2k/calculations/__init__.py
- aiida_cp2k/parsers/__init__.py
- aiida_cp2k/utils/datatype_helpers.py
- aiida_cp2k/utils/parser.py
- aiida_cp2k/utils/workchains.py
- aiida_cp2k/workchains/base.py
- conftest.py
- docs/source/conf.py
- examples/gaussian_datatypes/example_automatic.py
- examples/gaussian_datatypes/example_explicit.py
- examples/gaussian_datatypes/gdt_data.py
- examples/single_calculations/example_bands.py
- examples/single_calculations/example_dft.py
- examples/single_calculations/example_dft_atomic_kinds.py
- examples/single_calculations/example_failure.py
- examples/single_calculations/example_geopt.py
- examples/single_calculations/example_max_error.py
- examples/single_calculations/example_mm.py
- examples/single_calculations/example_multiple_force_eval.py
- examples/single_calculations/example_no_struct.py
- examples/single_calculations/example_precision.py
- examples/single_calculations/example_restart.py
- examples/single_calculations/example_structure_through_file.py
- examples/workchains/example_base_energy_restart.py
- examples/workchains/example_base_failed_restart.py
- examples/workchains/example_base_geoopt_restart.py
- test/test_gaussian_datatypes.py
- test/test_xyz.py
Pylint was disabled a long time ago. This PR removes all the leftover warning disabling.
> Remove the pylint warning disablings

- aiida_cp2k/parsers/__init__.py
- aiida_cp2k/utils/parser.py
- examples/single_calculations/example_restart.py
> Fix: retrieve the last structure even if the calculation has failed.

- aiida_cp2k/parsers/__init__.py
symbols of a trajectory cannot contain digits
> fix bug in creation of trajectory
